server:
  port: 8080
spring:
  datasource:
    username: root
    password: "036391"
    url: jdbc:mysql://localhost:3306/gmall_study?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#日志级别
#logging:
#  level:
#    com:
#      atguigu:
#        gmall: debug

