server:
  port: 8087
spring:
  datasource:
    username: root
    password: "036391"
    url: jdbc:mysql://localhost:3306/gmall_study?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application: gmall-payment
    protocol:
      name: dubbo
    registry:
      address: 192.168.1.128:2181
      protocol: zookeeper
    base-package: com.atguigu.gmall
    consumer:
      timeout: 6000
      check: false
  redis:
    host: 192.168.1.128
    port: 6379
    database: 0
  thymeleaf:
    cache: false
    #松校验
    mode: LEGACYHTML5
    #mq消息端口tcp协议
  activemq:
    broker-url: tcp://localhost:61616
    #开启监听
    listener:
      enable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true