server:
  port: 9001
spring:
  datasource:
    username: root
    password: "036391"
    url: jdbc:mysql://localhost:3306/gmall_study?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    listener:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  enum-as-simple-type: true

order:
  split:
    url: http://order.gmall.com/orderSplit

